# Generated by Django 3.2.16 on 2022-12-10 19:29

from django.db import migrations, models
import djangoFinal.blog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='C:\\Users\\vlado\\PycharmProjects\\djangoFinal\\staticfiles/images/none.png', upload_to='staticfiles/images', validators=[djangoFinal.blog.validators.validate_image_size]),
        ),
    ]
