# Generated by Django 3.2.16 on 2022-12-10 19:44

from django.db import migrations, models
import djangoFinal.blog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newsletteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='C:\\Users\\vlado\\PycharmProjects\\djangoFinal\\staticfiles/images/none.png', upload_to='images', validators=[djangoFinal.blog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='C:\\Users\\vlado\\PycharmProjects\\djangoFinal\\staticfiles/images/none.png', upload_to='images', validators=[djangoFinal.blog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='C:\\Users\\vlado\\PycharmProjects\\djangoFinal\\staticfiles/images/none.png', upload_to='images', validators=[djangoFinal.blog.validators.validate_image_size]),
        ),
    ]
