# Generated by Django 3.2.16 on 2022-12-13 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='job_position',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
