# Generated by Django 3.2.16 on 2022-12-13 18:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20221213_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
